// Mock data for Members Page

export const MOCK_MEMBERS = [
  {
    id: 1,
    memberId: 1,
    userId: 1,
    userFullName: 'ALJAWHARY Fadi',
    email: 'fadi.aljawhary@devoteam.com',
    roleId: 1,
    roleName: 'Chairperson',
    roleArabicName: 'رئيس اللجنة',
    status: 'active',
    organization: 'IT Department',
    department: 'Technology',
    startDate: '2024-01-15',
    endDate: null,
    notes: 'Committee chairperson since formation',
    isExternal: false,
  },
  {
    id: 2,
    memberId: 2,
    userId: 2,
    userFullName: 'QUBLAN Anas',
    email: 'anas.qublan@devoteam.com',
    roleId: 2,
    roleName: 'Vice Chairperson',
    roleArabicName: 'نائب رئيس اللجنة',
    status: 'active',
    organization: 'Operations',
    department: 'Management',
    startDate: '2024-01-15',
    endDate: null,
    notes: '',
    isExternal: false,
  },
  {
    id: 3,
    memberId: 3,
    userId: 3,
    userFullName: 'Ahmed Ali',
    email: 'ahmed.ali@devoteam.com',
    roleId: 3,
    roleName: 'Secretary',
    roleArabicName: 'أمين السر',
    status: 'active',
    organization: 'Administration',
    department: 'Support',
    startDate: '2024-01-20',
    endDate: null,
    notes: '',
    isExternal: false,
  },
  {
    id: 4,
    memberId: 4,
    userId: 4,
    userFullName: 'ABUARQOB Mujahed',
    email: 'sarah.johnson@devoteam.com',
    roleId: 4,
    roleName: 'Member',
    roleArabicName: 'عضو',
    status: 'active',
    organization: 'Finance',
    department: 'Accounting',
    startDate: '2024-02-01',
    endDate: null,
    notes: '',
    isExternal: false,
  },
  {
    id: 5,
    memberId: 5,
    userId: 5,
    userFullName: 'Mohammed Hassan',
    email: 'mohammed.hassan@devoteam.com',
    roleId: 4,
    roleName: 'Member',
    roleArabicName: 'عضو',
    status: 'active',
    organization: 'HR',
    department: 'Human Resources',
    startDate: '2024-02-15',
    endDate: null,
    notes: '',
    isExternal: false,
  },
  {
    id: 6,
    memberId: 6,
    userId: null,
    userFullName: 'External Consultant',
    email: 'consultant@external.com',
    roleId: 4,
    roleName: 'Member',
    roleArabicName: 'عضو',
    status: 'active',
    organization: 'External',
    department: 'Consulting',
    startDate: '2024-03-01',
    endDate: '2024-12-31',
    notes: 'External consultant for Q4 2024',
    isExternal: true,
    company: 'Consulting Firm Inc.',
    title: 'Senior Consultant',
  },
  {
    id: 7,
    memberId: 7,
    userId: 6,
    userFullName: 'Fatima Ahmed',
    email: 'fatima.ahmed@devoteam.com',
    roleId: 4,
    roleName: 'Member',
    roleArabicName: 'عضو',
    status: 'inactive',
    organization: 'Marketing',
    department: 'Communications',
    startDate: '2024-01-15',
    endDate: '2024-11-30',
    notes: 'Member until November 2024',
    isExternal: false,
  },
];

export const MOCK_ROLES = [
  { id: 1, name: 'Chairperson', arabicName: 'رئيس اللجنة' },
  { id: 2, name: 'Vice Chairperson', arabicName: 'نائب رئيس اللجنة' },
  { id: 3, name: 'Secretary', arabicName: 'أمين السر' },
  { id: 4, name: 'Member', arabicName: 'عضو' },
];

export const MOCK_ORGANIZATIONS = ['IT Department', 'Operations', 'Administration', 'Finance', 'HR', 'Marketing', 'External'];

export const MOCK_DEPARTMENTS = ['Technology', 'Management', 'Support', 'Accounting', 'Human Resources', 'Communications', 'Consulting'];
