import { LayoutDashboard, Users, Calendar, CheckSquare, Target, FileText, Newspaper, Clock, FileTextIcon, MessageCircle } from 'lucide-react';

export const PRIVATE_ROUTES = [
  {
    id: 0,
    path: `/home`,
    key: 'landing-page',
    label: 'landingPage',
    element: 'LandingPage',
    showInSidebar: false,
  },
  {
    id: 1,
    path: `/`,
    key: 'home',
    label: 'home',
    element: 'HomePage',
    showInSidebar: false,
  },
  {
    id: 2,
    path: `/notifications`,
    key: 'notifications',
    label: 'Notifications',
    element: 'NotificationsPage',
    showInSidebar: false,
  },
  {
    id: 3,
    path: `/committees/create`,
    key: 'create-committee',
    label: 'createCommittee',
    element: 'CreateCommitteeForm',
    showInSidebar: false,
  },
  {
    id: 4,
    path: `/committees/update/:committeeId`,
    key: 'update-committee',
    label: 'updateCommittee',
    element: 'UpdateCommitteeForm',
    showInSidebar: false,
  },
  {
    id: 5,
    path: `/councils/create`,
    key: 'create-council',
    label: 'createCouncil',
    element: 'CreateCouncilForm',
    showInSidebar: false,
  },
  {
    id: 6,
    path: `/councils/update/:councilId`,
    key: 'update-council',
    label: 'updateCouncil',
    element: 'UpdateCouncilForm',
    showInSidebar: false,
  },
  {
    id: 18,
    path: `/meetings/create`,
    key: 'create-meeting',
    label: 'createMeeting',
    element: 'CreateMeetingForm',
    showInSidebar: false,
  },
  {
    id: 19,
    path: `/meetings/update/:meetingId`,
    key: 'update-meeting',
    label: 'updateMeeting',
    element: 'UpdateMeetingForm',
    showInSidebar: false,
  },
  {
    id: 21,
    path: `/news/create`,
    key: 'create-announcement',
    label: 'createAnnouncement',
    element: 'CreateAnnouncementForm',
    showInSidebar: false,
  },
  {
    id: 22,
    path: `/news/update/:id`,
    key: 'update-announcement',
    label: 'updateAnnouncement',
    element: 'UpdateAnnouncementForm',
    showInSidebar: false,
  },
  {
    id: 23,
    path: `/tasks/create`,
    key: 'create-task',
    label: 'createTask',
    element: 'CreateTaskForm',
    showInSidebar: false,
  },
  {
    id: 24,
    path: `/tasks/update/:id`,
    key: 'update-task',
    label: 'updateTask',
    element: 'UpdateTaskForm',
    showInSidebar: false,
  },
  {
    id: 25,
    path: `/voting/create`,
    key: 'create-vote',
    label: 'createVote',
    element: 'CreateVoteForm',
    showInSidebar: false,
  },
  {
    id: 26,
    path: `/voting/update/:id`,
    key: 'update-vote',
    label: 'updateVote',
    element: 'UpdateVoteForm',
    showInSidebar: false,
  },

  // Sidebar pages
  {
    id: 7,
    path: `/overview`,
    key: 'overview',
    label: 'overview',
    element: 'OverviewPage',
    icon: LayoutDashboard,
    showInSidebar: true,
  },
  {
    id: 8,
    path: `/members`,
    key: 'members',
    label: 'members',
    element: 'MembersPage',
    icon: Users,
    showInSidebar: true,
  },
  {
    id: 9,
    path: `/meetings`,
    key: 'meetings',
    label: 'meetings',
    element: 'MeetingsPage',
    icon: Calendar,
    showInSidebar: true,
  },
  {
    id: 16,
    path: `/messages`,
    key: 'messages',
    label: 'messages',
    element: 'MessagesPage',
    icon: MessageCircle,
    showInSidebar: true,
  },
  // {
  //   id: 10,
  //   path: `/decisions`,
  //   key: 'decisions',
  //   label: 'decisions',
  //   element: 'DecisionsPage',
  //   icon: CheckSquare,
  //   showInSidebar: true,
  // },
  {
    id: 11,
    path: `/voting`,
    key: 'voting',
    label: 'voting',
    element: 'VotingPage',
    icon: Target,
    showInSidebar: true,
  },
  {
    id: 12,
    path: `/tasks`,
    key: 'tasks',
    label: 'tasks',
    element: 'TasksPage',
    icon: CheckSquare,
    showInSidebar: true,
  },
  // {
  //   id: 13,
  //   path: `/documents`,
  //   key: 'documents',
  //   label: 'documents',
  //   element: 'DocumentsPage',
  //   icon: FileText,
  //   showInSidebar: true,
  // },
  {
    id: 14,
    path: `/news`,
    key: 'news',
    label: 'news',
    element: 'NewsPage',
    icon: Newspaper,
    showInSidebar: true,
  },
  {
    id: 15,
    path: `/calendar`,
    key: 'calendar',
    label: 'calendar',
    element: 'CalendarPage',
    icon: Calendar,
    showInSidebar: true,
  },

  // Details Pages
  {
    id: 17,
    path: `/meetings/:meetingId`,
    key: 'meeting-details',
    label: 'meetingDetails',
    element: 'MeetingsDetailsPage',
    showInSidebar: false,
  },
  {
    id: 20,
    path: `/news/:id`,
    key: 'news-details',
    label: 'newsDetails',
    element: 'NewsDetailsPage',
    showInSidebar: false,
  },
];
