// Mock data for Meetings Page

export const MOCK_MEETINGS = [
  {
    id: 1,
    title: 'Monthly Review Meeting',
    arabicTitle: 'اجتماع المراجعة الشهرية',
    type: 'regular', // regular, emergency, virtual, physical
    date: '2024-12-20',
    startTime: '10:00',
    endTime: '12:00',
    location: 'Conference Room A',
    isOnline: false,
    meetingLink: null,
    status: 'upcoming', // upcoming, in_progress, completed, cancelled, postponed
    organizerId: 1,
    organizerName: 'ALJAWHARY Fadi',
    agendaItemsCount: 5,
    attachmentsCount: 3,
    participantsCount: 12,
    momStatus: null, // null, draft, published
    attendanceStatus: null, // null, recorded
    committeeId: 1,
  },
  {
    id: 2,
    title: 'Emergency Board Meeting',
    arabicTitle: 'اجتماع الطوارئ للمجلس',
    type: 'emergency',
    date: '2024-12-18',
    startTime: '14:00',
    endTime: '16:00',
    location: null,
    isOnline: true,
    meetingLink: 'https://meet.example.com/abc123',
    status: 'completed',
    organizerId: 1,
    organizerName: 'ALJAWHARY Fadi',
    agendaItemsCount: 3,
    attachmentsCount: 2,
    participantsCount: 10,
    momStatus: 'published',
    attendanceStatus: 'recorded',
    committeeId: 1,
  },
  {
    id: 3,
    title: 'Strategic Planning Session',
    arabicTitle: 'جلسة التخطيط الاستراتيجي',
    type: 'regular',
    date: '2024-12-15',
    startTime: '09:00',
    endTime: '17:00',
    location: 'Main Hall',
    isOnline: false,
    meetingLink: null,
    status: 'completed',
    organizerId: 2,
    organizerName: 'QUBLAN Anas',
    agendaItemsCount: 8,
    attachmentsCount: 5,
    participantsCount: 15,
    momStatus: 'draft',
    attendanceStatus: 'recorded',
    committeeId: 1,
  },
  {
    id: 4,
    title: 'Budget Discussion',
    arabicTitle: 'مناقشة الميزانية',
    type: 'regular',
    date: '2024-12-22',
    startTime: '11:00',
    endTime: '13:00',
    location: null,
    isOnline: true,
    meetingLink: 'https://meet.example.com/xyz789',
    status: 'upcoming',
    organizerId: 3,
    organizerName: 'Ahmed Ali',
    agendaItemsCount: 4,
    attachmentsCount: 1,
    participantsCount: 8,
    momStatus: null,
    attendanceStatus: null,
    committeeId: 1,
  },
  {
    id: 5,
    title: 'Quarterly Review',
    arabicTitle: 'المراجعة الربع سنوية',
    type: 'regular',
    date: '2024-12-10',
    startTime: '10:00',
    endTime: '12:00',
    location: 'Conference Room B',
    isOnline: false,
    meetingLink: null,
    status: 'cancelled',
    organizerId: 1,
    organizerName: 'ALJAWHARY Fadi',
    agendaItemsCount: 6,
    attachmentsCount: 0,
    participantsCount: 0,
    momStatus: null,
    attendanceStatus: null,
    committeeId: 1,
  },
  {
    id: 6,
    title: 'Policy Review Meeting',
    arabicTitle: 'اجتماع مراجعة السياسات',
    type: 'regular',
    date: '2024-12-25',
    startTime: '15:00',
    endTime: '17:00',
    location: 'Virtual',
    isOnline: true,
    meetingLink: 'https://meet.example.com/policy123',
    status: 'postponed',
    organizerId: 2,
    organizerName: 'QUBLAN Anas',
    agendaItemsCount: 3,
    attachmentsCount: 2,
    participantsCount: 10,
    momStatus: null,
    attendanceStatus: null,
    committeeId: 1,
  },
];

export const MOCK_MEETING_TYPES = [
  { id: 'regular', name: 'Regular', arabicName: 'عادي' },
  { id: 'emergency', name: 'Emergency', arabicName: 'طوارئ' },
  { id: 'virtual', name: 'Virtual', arabicName: 'افتراضي' },
  { id: 'physical', name: 'Physical', arabicName: 'حضوري' },
];

export const MOCK_MEETING_STATUSES = [
  { id: 'upcoming', name: 'Upcoming', arabicName: 'قادم' },
  { id: 'in_progress', name: 'In Progress', arabicName: 'قيد التنفيذ' },
  { id: 'completed', name: 'Completed', arabicName: 'مكتمل' },
  { id: 'cancelled', name: 'Cancelled', arabicName: 'ملغي' },
  { id: 'postponed', name: 'Postponed', arabicName: 'مؤجل' },
];

// Static data for meeting with id: 1
export const MOCK_AGENDA_ITEMS = [
  {
    id: 1,
    meetingId: 1,
    order: 1,
    title: 'Review Q4 Performance',
    arabicTitle: 'مراجعة أداء الربع الرابع',
    description: 'Review key performance indicators and metrics for Q4 2024',
    arabicDescription: 'مراجعة مؤشرات الأداء الرئيسية والمقاييس للربع الرابع 2024',
    duration: 30,
    presenter: 'ALJAWHARY Fadi',
    attachments: [],
  },
  {
    id: 2,
    meetingId: 1,
    order: 2,
    title: 'Budget Discussion',
    arabicTitle: 'مناقشة الميزانية',
    description: 'Discuss budget allocation for next quarter',
    arabicDescription: 'مناقشة تخصيص الميزانية للربع القادم',
    duration: 25,
    presenter: 'QUBLAN Anas',
    attachments: [],
  },
  {
    id: 3,
    meetingId: 1,
    order: 3,
    title: 'Strategic Planning',
    arabicTitle: 'التخطيط الاستراتيجي',
    description: 'Review and update strategic goals for 2025',
    arabicDescription: 'مراجعة وتحديث الأهداف الاستراتيجية لعام 2025',
    duration: 35,
    presenter: 'Ahmed Ali',
    attachments: [],
  },
  {
    id: 4,
    meetingId: 1,
    order: 4,
    title: 'Team Updates',
    arabicTitle: 'تحديثات الفريق',
    description: 'Updates from each department on current projects',
    arabicDescription: 'تحديثات من كل قسم حول المشاريع الحالية',
    duration: 20,
    presenter: 'ABUARQOB Mujahed',
    attachments: [],
  },
  {
    id: 5,
    meetingId: 1,
    order: 5,
    title: 'Open Discussion',
    arabicTitle: 'مناقشة مفتوحة',
    description: 'Open floor for questions and concerns',
    arabicDescription: 'منصة مفتوحة للأسئلة والاهتمامات',
    duration: 10,
    presenter: null,
    attachments: [],
  },
];

export const MOCK_PARTICIPANTS = [
  {
    id: 1,
    meetingId: 1,
    memberId: 1,
    userId: 1,
    userFullName: 'ALJAWHARY Fadi',
    email: 'fadi.ALJAWHARY@example.com',
    roleName: 'Chairperson',
    roleArabicName: 'رئيس اللجنة',
    attendanceStatus: null, // null, present, absent, late, excused
    isRequired: true,
    isExternal: false,
  },
  {
    id: 2,
    meetingId: 1,
    memberId: 2,
    userId: 2,
    userFullName: 'QUBLAN Anas',
    email: 'anas.qublan@example.com',
    roleName: 'Vice Chairperson',
    roleArabicName: 'نائب رئيس اللجنة',
    attendanceStatus: null,
    isRequired: true,
    isExternal: false,
  },
  {
    id: 3,
    meetingId: 1,
    memberId: 3,
    userId: 3,
    userFullName: 'Ahmed Ali',
    email: 'ahmed.ali@example.com',
    roleName: 'Secretary',
    roleArabicName: 'أمين السر',
    attendanceStatus: null,
    isRequired: true,
    isExternal: false,
  },
  {
    id: 4,
    meetingId: 1,
    memberId: 4,
    userId: 4,
    userFullName: 'ABUARQOB Mujahed',
    email: 'sarah.johnson@example.com',
    roleName: 'Member',
    roleArabicName: 'عضو',
    attendanceStatus: null,
    isRequired: true,
    isExternal: false,
  },
  {
    id: 5,
    meetingId: 1,
    memberId: 5,
    userId: 5,
    userFullName: 'Mohammed Hassan',
    email: 'mohammed.hassan@example.com',
    roleName: 'Member',
    roleArabicName: 'عضو',
    attendanceStatus: null,
    isRequired: false,
    isExternal: false,
  },
  {
    id: 6,
    meetingId: 1,
    memberId: 6,
    userId: null,
    userFullName: 'External Consultant',
    email: 'consultant@external.com',
    roleName: 'Guest',
    roleArabicName: 'ضيف',
    attendanceStatus: null,
    isRequired: false,
    isExternal: true,
    company: 'Consulting Firm Inc.',
    title: 'Senior Consultant',
  },
];

export const MOCK_MEETING_TASKS = [
  {
    id: 1,
    meetingId: 1,
    title: 'Prepare Q4 Performance Report',
    arabicTitle: 'إعداد تقرير أداء الربع الرابع',
    description: 'Compile and analyze all Q4 performance metrics and prepare comprehensive report',
    arabicDescription: 'تجميع وتحليل جميع مقاييس أداء الربع الرابع وإعداد تقرير شامل',
    assignedToId: 3,
    assignedToName: 'Ahmed Ali',
    dueDate: '2024-12-25',
    status: 'in_progress', // pending, in_progress, completed, cancelled
    priority: 'high', // low, medium, high, urgent
    createdFrom: 'agenda_item', // agenda_item, decision, mom
    createdFromId: 1,
    createdFromName: 'Review Q4 Performance',
    createdById: 1,
    createdByName: 'ALJAWHARY Fadi',
    createdAt: '2024-12-15T10:00:00',
    lastUpdated: '2024-12-18T14:30:00',
  },
  {
    id: 2,
    meetingId: 1,
    title: 'Draft Budget Proposal',
    arabicTitle: 'مسودة اقتراح الميزانية',
    description: 'Create detailed budget proposal for Q1 2025 based on discussion points',
    arabicDescription: 'إنشاء اقتراح ميزانية مفصل للربع الأول 2025 بناءً على نقاط المناقشة',
    assignedToId: 2,
    assignedToName: 'QUBLAN Anas',
    dueDate: '2024-12-28',
    status: 'pending',
    priority: 'high',
    createdFrom: 'agenda_item',
    createdFromId: 2,
    createdFromName: 'Budget Discussion',
    createdById: 1,
    createdByName: 'ALJAWHARY Fadi',
    createdAt: '2024-12-15T10:30:00',
    lastUpdated: '2024-12-15T10:30:00',
  },
  {
    id: 3,
    meetingId: 1,
    title: 'Update Strategic Goals Document',
    arabicTitle: 'تحديث وثيقة الأهداف الاستراتيجية',
    description: 'Review and update the strategic goals document with new objectives for 2025',
    arabicDescription: 'مراجعة وتحديث وثيقة الأهداف الاستراتيجية بأهداف جديدة لعام 2025',
    assignedToId: 4,
    assignedToName: 'ABUARQOB Mujahed',
    dueDate: '2025-01-05',
    status: 'pending',
    priority: 'medium',
    createdFrom: 'agenda_item',
    createdFromId: 3,
    createdFromName: 'Strategic Planning',
    createdById: 1,
    createdByName: 'ALJAWHARY Fadi',
    createdAt: '2024-12-15T11:00:00',
    lastUpdated: '2024-12-15T11:00:00',
  },
  {
    id: 4,
    meetingId: 1,
    title: 'Follow up on Department Updates',
    arabicTitle: 'متابعة تحديثات الأقسام',
    description: 'Contact each department head to gather project updates and compile summary',
    arabicDescription: 'الاتصال برئيس كل قسم لجمع تحديثات المشاريع وتجميع الملخص',
    assignedToId: 3,
    assignedToName: 'Ahmed Ali',
    dueDate: '2024-12-22',
    status: 'in_progress',
    priority: 'medium',
    createdFrom: 'agenda_item',
    createdFromId: 4,
    createdFromName: 'Team Updates',
    createdById: 1,
    createdByName: 'ALJAWHARY Fadi',
    createdAt: '2024-12-15T11:30:00',
    lastUpdated: '2024-12-17T09:15:00',
  },
  {
    id: 5,
    meetingId: 1,
    title: 'Review and Approve Meeting Minutes',
    arabicTitle: 'مراجعة والموافقة على محضر الاجتماع',
    description: 'Review the draft meeting minutes and provide approval',
    arabicDescription: 'مراجعة مسودة محضر الاجتماع والموافقة عليه',
    assignedToId: 1,
    assignedToName: 'ALJAWHARY Fadi',
    dueDate: '2024-12-21',
    status: 'completed',
    priority: 'low',
    createdFrom: 'mom',
    createdFromId: null,
    createdFromName: 'Minutes of Meeting',
    createdById: 3,
    createdByName: 'Ahmed Ali',
    createdAt: '2024-12-15T12:00:00',
    lastUpdated: '2024-12-19T16:45:00',
  },
];

// Mock Votes for Meeting Details
export const MOCK_MEETING_VOTES = [
  {
    id: 1,
    meetingId: 1,
    title: 'Approve Q4 Budget Proposal',
    arabicTitle: 'الموافقة على اقتراح ميزانية الربع الرابع',
    description: 'Vote to approve the proposed budget for Q4 2024',
    arabicDescription: 'التصويت على الموافقة على الميزانية المقترحة للربع الرابع 2024',
    agendaItemId: 2,
    agendaItemTitle: 'Budget Discussion',
    votingType: 'non_anonymous', // anonymous, non_anonymous
    votingMethod: 'yes_no_abstain', // yes_no_abstain, single_choice, multiple_choice
    status: 'completed', // not_started, in_progress, completed
    startTime: '2024-12-15T10:45:00',
    endTime: '2024-12-15T11:00:00',
    eligibleVoters: [1, 2, 3, 4, 5], // Member IDs
    eligibleVotersCount: 5,
    totalVotes: 5,
    results: {
      yes: { count: 4, percentage: 80 },
      no: { count: 0, percentage: 0 },
      abstain: { count: 1, percentage: 20 },
    },
    voters: [
      { memberId: 1, memberName: 'ALJOHARI Fadi', vote: 'yes', votedAt: '2024-12-15T10:46:00' },
      { memberId: 2, memberName: 'QUBLAN Anas', vote: 'yes', votedAt: '2024-12-15T10:47:00' },
      { memberId: 3, memberName: 'Ahmed Ali', vote: 'yes', votedAt: '2024-12-15T10:48:00' },
      { memberId: 4, memberName: 'ABUARQOB Mujahed', vote: 'yes', votedAt: '2024-12-15T10:49:00' },
      { memberId: 5, memberName: 'Mohammed Hassan', vote: 'abstain', votedAt: '2024-12-15T10:50:00' },
    ],
    createdById: 1,
    createdByName: 'ALJOHARI Fadi',
    createdAt: '2024-12-15T10:40:00',
  },
  {
    id: 2,
    meetingId: 1,
    title: 'Select Strategic Planning Approach',
    arabicTitle: 'اختيار نهج التخطيط الاستراتيجي',
    description: 'Choose the preferred approach for strategic planning 2025',
    arabicDescription: 'اختيار النهج المفضل للتخطيط الاستراتيجي 2025',
    agendaItemId: 3,
    agendaItemTitle: 'Strategic Planning',
    votingType: 'non_anonymous',
    votingMethod: 'single_choice',
    status: 'in_progress',
    startTime: '2024-12-15T11:15:00',
    endTime: null,
    eligibleVoters: [1, 2, 3, 4, 5],
    eligibleVotersCount: 5,
    totalVotes: 2,
    options: [
      { id: 1, label: 'Traditional Approach', arabicLabel: 'النهج التقليدي', votes: 1, percentage: 50 },
      { id: 2, label: 'Agile Approach', arabicLabel: 'النهج المرن', votes: 1, percentage: 50 },
      { id: 3, label: 'Hybrid Approach', arabicLabel: 'النهج المختلط', votes: 0, percentage: 0 },
    ],
    voters: [
      { memberId: 1, memberName: 'ALJOHARI Fadi', vote: 'Traditional Approach', votedAt: '2024-12-15T11:16:00' },
      { memberId: 2, memberName: 'QUBLAN Anas', vote: 'Agile Approach', votedAt: '2024-12-15T11:17:00' },
    ],
    createdById: 1,
    createdByName: 'ALJOHARI Fadi',
    createdAt: '2024-12-15T11:10:00',
  },
  {
    id: 3,
    meetingId: 1,
    title: 'Approve New Committee Member',
    arabicTitle: 'الموافقة على عضو جديد في اللجنة',
    description: 'Vote to approve the new committee member application',
    arabicDescription: 'التصويت على الموافقة على طلب عضو جديد في اللجنة',
    agendaItemId: null,
    agendaItemTitle: null,
    votingType: 'anonymous',
    votingMethod: 'yes_no_abstain',
    status: 'not_started',
    startTime: null,
    endTime: null,
    eligibleVoters: [1, 2, 3, 4],
    eligibleVotersCount: 4,
    totalVotes: 0,
    results: null,
    voters: [],
    createdById: 1,
    createdByName: 'ALJOHARI Fadi',
    createdAt: '2024-12-15T11:30:00',
  },
];
